// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BwvqeOioBeopVXHHb3EXU1XVfzRKOgs',
    appId: '1:80902058409:web:3177729c84deaaff4194b8',
    messagingSenderId: '80902058409',
    projectId: 'discoverethiopia-38c5c',
    authDomain: 'discoverethiopia-38c5c.firebaseapp.com',
    storageBucket: 'discoverethiopia-38c5c.appspot.com',
    measurementId: 'G-Y54TSHJ2S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8FSYuqpOzyZR9B9dIbiDkgBL92n7M1Q',
    appId: '1:80902058409:android:93123cbadbf337724194b8',
    messagingSenderId: '80902058409',
    projectId: 'discoverethiopia-38c5c',
    storageBucket: 'discoverethiopia-38c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPZIwxjAlg_LdiFoHEge6tJyiJM_MH1Jc',
    appId: '1:80902058409:ios:b33c2b7c9c7f03b24194b8',
    messagingSenderId: '80902058409',
    projectId: 'discoverethiopia-38c5c',
    storageBucket: 'discoverethiopia-38c5c.appspot.com',
    iosClientId: '80902058409-qb9mpgrhre56mmkdbmd4evtdecpk34je.apps.googleusercontent.com',
    iosBundleId: 'csec.alphawarriors.discoverEthiopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPZIwxjAlg_LdiFoHEge6tJyiJM_MH1Jc',
    appId: '1:80902058409:ios:92399cf411bd20c94194b8',
    messagingSenderId: '80902058409',
    projectId: 'discoverethiopia-38c5c',
    storageBucket: 'discoverethiopia-38c5c.appspot.com',
    iosClientId: '80902058409-5mh45mk01o9111cm54t40ioi9ujjns1u.apps.googleusercontent.com',
    iosBundleId: 'csec.alphawarriors.discoverEthiopia.RunnerTests',
  );
}
